# Generated by Django 3.2.12 on 2022-05-12 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('title', models.CharField(max_length=100, verbose_name='Mavzu')),
                ('body', models.CharField(max_length=1000, verbose_name='Xabar matni')),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='accept_book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Муаллифи'),
        ),
        migrations.AddField(
            model_name='accept_book',
            name='respite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=100, verbose_name='Муаллифи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return_book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Муаллифи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=100, verbose_name='Китоб номи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='key',
            field=models.CharField(max_length=25, verbose_name='Инвентар рақами'),
        ),
        migrations.AlterField(
            model_name='return_book',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='olingan vaqti'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
    ]
