# Generated by Django 3.2.12 on 2022-05-13 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220513_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accept_book',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='adminhod',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='emplayeemessages',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='return_book',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='sendmessages',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='accept_book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emplayeemessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='return_book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
