# Generated by Django 3.2.12 on 2022-05-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220513_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_book',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs'),
        ),
        migrations.AddField(
            model_name='return_book',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs'),
        ),
    ]
