# Generated by Django 3.2.12 on 2022-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220514_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_book',
            name='author',
            field=models.CharField(default=1, max_length=100, verbose_name='Муаллифи'),
            preserve_default=False,
        ),
    ]
