# Generated by Django 3.2.12 on 2022-05-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accept_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept_book',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_book', to='accounts.students'),
        ),
    ]
