# Generated by Django 3.2.12 on 2022-05-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_return_book_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_book',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students'),
        ),
    ]
