# Generated by Django 3.2.12 on 2022-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220601_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=25),
        ),
    ]
