# Generated by Django 3.2.12 on 2022-06-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220603_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='password_ID',
            new_name='passport_id',
        ),
        migrations.AddField(
            model_name='students',
            name='FIO',
            field=models.CharField(default=123, max_length=500, verbose_name='FIO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='JSHSHIR',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='Talim turi',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='brithday',
            field=models.CharField(default=23423432, max_length=100, verbose_name='Tugulgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(default=131231, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='faculty',
            field=models.CharField(default=1231312321312, max_length=300, verbose_name='Fakultet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='formofEducation',
            field=models.CharField(default=8765, max_length=100, verbose_name='Talim shakli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='formofPayment',
            field=models.CharField(default=1, max_length=100, verbose_name='Tolov shakli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='fuqarolik',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default=1, max_length=50, verbose_name='jins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='nationaly',
            field=models.CharField(default=1, max_length=100, verbose_name='Millat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='previouseducationInformation',
            field=models.CharField(default=1, max_length=500, verbose_name='Avvalgi talim malumoti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='region',
            field=models.CharField(default=1, max_length=100, verbose_name='viloyat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='tuman',
            field=models.CharField(default=1, max_length=100, verbose_name='tuman'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='groups',
            field=models.CharField(default=1, max_length=50, verbose_name='guruhi'),
            preserve_default=False,
        ),
    ]
