# Generated by Django 3.2.12 on 2022-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220603_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='tuman',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tuman'),
        ),
    ]
