# Generated by Django 3.2.12 on 2022-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220604_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adadi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адади'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Муаллифи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='beti',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бети'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Китоб номи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Шахар номи'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='key',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Инвентар рақами'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='money',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='book',
            name='nameda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номда'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сонда'),
        ),
        migrations.AlterField(
            model_name='book',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тавсия қилган ташкилот'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Нашриёт'),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бўлими'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Йили'),
        ),
    ]
