# Generated by Django 3.2.12 on 2022-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_return_book_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_book',
            name='respite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
