# Generated by Django 3.2.12 on 2022-06-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_return_book_respite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book_name', models.CharField(max_length=50, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=100, verbose_name='Муаллифи')),
                ('date', models.DateField(blank=True, null=True, verbose_name='olingan vaqti')),
                ('key', models.CharField(max_length=25)),
                ('respite', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='BookType',
        ),
        migrations.DeleteModel(
            name='Langugae',
        ),
    ]
