# Generated by Django 3.2.12 on 2022-06-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220607_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='staff',
        ),
    ]
