# Generated by Django 3.2.12 on 2022-06-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_check_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='respite',
        ),
    ]
