# Generated by Django 3.2.12 on 2022-06-07 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_return_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
