# Generated by Django 3.2.12 on 2022-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20220607_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='formofPayment',
        ),
        migrations.RemoveField(
            model_name='students',
            name='previouseducationInformation',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=50, verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
