# Generated by Django 3.2.12 on 2022-06-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20220607_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept_book',
            name='staff',
            field=models.CharField(default=1, max_length=100, verbose_name='Bergan odam nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='return_book',
            name='staff',
            field=models.CharField(default=1, max_length=100, verbose_name='Bergan odam nomi'),
            preserve_default=False,
        ),
    ]
